version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    restart: always
    volumes:
      - project_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

volumes:
  project_db:
