"""empty message

Revision ID: e7ac84cf627a
Revises: eee251822cff
Create Date: 2025-02-10 12:37:04.407690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7ac84cf627a"
down_revision: Union[str, None] = "eee251822cff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("code", sa.UUID(), nullable=False),
        sa.Column("expired_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_code"), "token", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_code"), table_name="token")
    op.drop_table("token")
    # ### end Alembic commands ###
